version: '2'
services:
  plex:
    image: plexinc/pms-docker
    volumes:
      - plex_config:/config
      - transcode:/transcode 
      - /storage/Movies:/media/movies/ 
      - /storage/anime/:/media/anime/
      - /storage/TvShows/:/media/tvshows/
    ports:
      - 32400:32400/tcp
      - 3005:3005/tcp
      - 8324:8324/tcp
      - 32469:32469/tcp
      - 1900:1900/udp
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
    environment:
      - PLEX_CLAIM="claim-M7b65bZNTqcnoSipuUUh"
volumes:
  plex_config:
  transcode:
