version: '2'
services:
  plex:
    image: plexinc/pms-docker
    volumes:
      - plex_config:/config
      - transcode:/transcode 
      - /storage/Movies:/media/movies/ 
      - /storage/anime/:/media/anime/
      - /storage/TvShows/:/media/tvshows/
    ports:
      - 32400:32400
      -p 3005:3005
      -p 8324:8324
      -p 32469:32469
      -p 1900:1900
      -p 32410:32410
      -p 32412:32412
      -p 32413:32413
      -p 32414:32414
volumes:
  plex_config:
  transcode:
