version: '2'
services:
  plex:
    image: plexinc/pms-docker
    volumes:
      - plex_config:/config
      - transcode:/transcode 
      - /storage/Movies:/media/movies/ 
      - /storage/anime/:/media/anime/
      - /storage/TvShows/:/media/tvshows/
    ports:
      - 32400:32400
      - 3005:3005
      - 8324:8324
      - 32469:32469
      - 1900:1900
      - 32410:32410
      - 32412:32412
      - 32413:32413
      - 32414:32414
volumes:
  plex_config:
  transcode:
