version: '2'
services:
  plex:
    image: plexinc/pms-docker
    volumes:
      - plex_config:/config
      - transcode:/transcode 
      - /storage/Movies:/media/movies/ 
      - /storage/anime/:/media/anime/
      - /storage/TvShows/:/media/tvshows/
    ports:
      - 32400:32400
volumes:
  plex_config:
  transcode:
